[program:campaign-email-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan app:send-campaign-emails
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/campaign-email-worker.log
stderr_logfile=/var/log/supervisor/campaign-email-worker.err.log